# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target '爱服务' do
pod 'pop', '~> 1.0'

end

target '爱服务Tests' do

end

target '爱服务UITests' do

end

